[package]
name = "holomorph"
version = "0.1.0"
authors = ["scalexm <martin.alex32@hotmail.fr>"]

[dependencies]
rand = "*"
log = "*"
env_logger = "*"
time = "*"
rustc-serialize = "*"
postgres = "*"
lazy_static = "*"
shared = { path = "src/shared" }
protocol = { path = "src/protocol" }

[profile.release]
debug = true

[dependencies.eventual]
git = "https://github.com/carllerche/eventual"

[[bin]]
name = "auth"
path = "src/auth/main.rs"

[[bin]]
name = "game"
path = "src/game/main.rs"

[[test]]
name = "test"
path = "test/test.rs"
