[package]
name = "holomorph"
version = "0.1.0"
authors = ["scalexm <martin.alex32@hotmail.fr>"]

[dependencies]
rand = "*"
log = "*"
env_logger = "*"
time = "*"
rustc-serialize = "*"
postgres = "*"
byteorder = "*"
mio = "*"

[[bin]]
name = "auth"
path = "src/auth/main.rs"

[[test]]
name = "test"
path = "test/test.rs"

[lib]
name = "shared"
path = "src/shared/lib.rs"
