[package]
name = "protocol_gen"
version = "0.1.0"
authors = ["scalexm <alexandre@scalexm.fr>"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
docopt = "1"
