[package]
name = "protocol_derive"
version = "0.1.0"
authors = ["scalexm <alexandre@scalexm.fr>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
syn = "0.15"
quote = "0.6"

[dev-dependencies]
protocol = { path = "../protocol" }
